### ISSUE TITLE
Distribution on F-Droid

### ISSUE THREAD

**Issue by DragoonAethis** [SyncedSynapse/Kore#1]
Since there are quite a few devices without Google Play (either because Amazon and Friends or willingly), F-Droid would be a good place to distribute the app for everyone else. https://f-droid.org/

**Comment by SyncedSynapse** [comment]
I'll look into it, though i guess it can't be distributed as-is because there's currently a dependency on Google Play services which kind of defeats the purpose of F-Droid.

**Comment by SyncedSynapse** [comment]
(Fat fingers on previous close)

**Comment by logomancer** [comment]
Integrating [Dominik Schuermann's Android Donations Library](https://github.com/dschuermann/android-donations-lib) may be a way forward. This would also let you support donations out of Google Play.

**Comment by SyncedSynapse** [comment]
Thanks for pointing that out. My issue wasn't the donations, it's that there needs to be different build configurations (product flavours in Android speak), and i still haven't used them. Shouldn't be hard, but i want to get the bugs out and do a little more polish first.

**Comment by krt16s** [comment]
I don't see play-services dependency within the source, is it just required to be installed on the system? We add an antifeature to such apps, but we can (and do) build them. Not all of ours users are able (or want) to have a enitrely google free phone...

**Comment by SyncedSynapse** [comment]
You're correct, my previous comment was wrong: it doesn't depend on Play services, but it does use Google Play in-app billing.
Do you know if this is acceptable on F-Droid?

**Comment by krt16s** [comment]
As long as no non-free stuff is required at build time (doesn't look that way), we can build and ship it. As I said, I will mark it with an "anti feature", NonFreeDep in this case:

> the application depends on a non-free application (e.g. Google Maps) - i.e. it requires it to be installed on the device, but does not include it.

Being not familiar with in-app billing, what is the point of the IAP_KEY? As we don't use api keys and such, will the app still be usable if we just use "foobar" as key?

**Comment by SyncedSynapse** [comment]
IAP_KEY is the key that's used to validate responses from Google Play. It might show some errors if not set correctly. If you want the correct one, drop me an email and i'll send it (synced.synapse gmail).

Sorry, but i'm not familiar with the submission process on F-Droid. What am i supposed to do to submit it?

**Comment by krt16s** [comment]
Well, sending it to me would be essentialy the same as including it in the source repo, since we publish sourcecode for every build: Users shouldn't be required to trust us, but should be able to operate acomplete fdroid instance themselves, building everything on their own systems.. if they want to. Such a publication of the key will most likely not be covered by the TOS you agreed to, but I might be wrong.

I just enabled the build in 0d87c2ba6eb06c41f0100aebd9aacdf85911fb89 since it builds, installs and startsup fine. I cannot test it anyfurther as I don't have Kodi installed. I'll post the apk tomorrow when the buildservers has finished, so you can have a look at it.

**Comment by SyncedSynapse** [comment]
Ok, i'll take a look tomorrow.

**Comment by krt16s** [comment]
Apk is available here https://f-droid.org/repository/browse/?fdid=com.syncedsynapse.kore2 , direct dl: https://f-droid.org/repo/com.syncedsynapse.kore2_3.apk

**Comment by logomancer** [comment]
Looks good. In-app purchases are broken, as expected, which means that there's no way to unlock the custom themes. But other functionality works fine.

**Comment by krt16s** [comment]
@SyncedSynapse, is there a link for alternative donation methods you want to add?

**Comment by SyncedSynapse** [comment]
It is blowing up as soon as you enter the settings, which is not supposed to. I'll take a look to check what can be done. Integrating with Google Play won't be possible, but it shouldn't blow up.

@krt16s No thanks.

**Comment by SyncedSynapse** [comment]
@logomancer Can you please confirm that you can access the settings page?
It's throwing an exception on my account, but i suspect it might be my configuration.

**Comment by logomancer** [comment]
This is what I get when I try to access the settings menu: https://docs.google.com/file/d/0B5GHfURMehx2VzZIOENLUFVXNVk/

Running on a Galaxy S4 running OmniROM 4.4.

**Comment by SyncedSynapse** [comment]
@logomancer Thank you very much. It's what i suspected. I guess that behavior is acceptable.

2 quastions:
- How will the f-droid version be updated?
- Can i close this issue?

**Comment by DragoonAethis** [comment]
AFAIK F-Droid rebuilds the app whenever a new tag/release is made: https://f-droid.org/wiki/page/FAQ_-_App_Developers#Do_I_need_to_tell_you_when_I_update.3F - and yes, it's good to close. Thanks! :)
