### ISSUE TITLE
[Feature Request] CD Cover in Remote screen aspect ratio

### ISSUE THREAD

**Issue by 2Zero** [SyncedSynapse/Kore#13]
When in the remote control screen, the aspect ratio for CD covers is that of a DVD cover.

Could this be square instead (as it is when browsing Album details)?

**Comment by SyncedSynapse** [comment]
Changed in 40fca3f9bc41916e8ff94e1bc08f6e40bc8c6c17

This applies to the the "Now playing" and the "Playlist" screen, though not to the "Remote" screen, as it looks very unbalanced. There's commented code in RemoteFragment.java to enable it if you'd like to try it.
