### ISSUE TITLE
Remote - missing "Title" button

### ISSUE THREAD

**Issue by tasn** [SyncedSynapse/Kore#19]
Hey,

On the XBMC remote (the obsolete open source one), there's a button called "Title" that let's you get into extra menus and is useful. A good example is to go from the main kodi screen to:
Videos -> Files
You now need the "Title" button in order to expose the extra menu that will let you rescan content and etc. Kore has "Codec" instead of the "Title" button, which does nothing in this case.

Thanks.

**Comment by SyncedSynapse** [comment]
Done 9466d9e0a897433b9ca2468bbfbdb1f0b4986da1

**Comment by tasn** [comment]
Thanks for the quick resolution.
