### ISSUE TITLE
Now playing notification persists on Kore shutdown.

### ISSUE THREAD

**Issue by 2Zero** [SyncedSynapse/Kore#31]
If Kore is closed whilst the now playing notification is displayed, the now playing notification persists (i.e. it doesn't go away). The notification no longer updates with the current item being played on Kodi and only disappears when either reaped by Android or Kore is restarted and a new item played.

Expected behaviour (from a user perspective), notification closes with Kore.

Devices tested: HTC M8 & Nexus 7

**Comment by SyncedSynapse** [comment]
Well, there's no concept of closing an app in Android, and the Now playing notification is supposed to be on while there's something playing, even if the user is not in Kore (that's the purpose of notifications).

The notification should be present as long as: 1) there's something playing in kore and 2) it can maintain a connection. "Closing" or exiting Kore, even removing it from the recent apps, shouldn't affect the notification.
While the notification is on, it should update itself with the information about what is playing, though if what's playing finishes or is stopped, the notification should disappear, and it is not restarted. Some scenarios:
1. The notification is on, the video that is currently playing finishes - the notification is removed. The user starts another one, not using Kore - the notification isn't shown. If it is started from within Kore, the notification should appear.
2. The notification is on, the current item finishes, and something else immediately starts playing (it's on a playlist) -  the notification is kept, with updated information.
3. The notification is on, something is playing and the user starts something else (not stopping the previous one), from within or outside Kore  -  the notification is kept, with updated information.

I'm going to close this issue, but if the above behaviour isn't what's happening, please reopen it or create a new one with an updated title.
