### ISSUE TITLE
Now playing notification persists on Kore removal from recent apps.

### ISSUE THREAD

**Issue by 2Zero** [SyncedSynapse/Kore#32]
Thank you for taking the time to comprehensively reply to #31. I don't have rights to reopen the issue so creating this to comment, hope that's okay.

The notification behaves exactly as you described in #31 except:

> removing it from the recent apps, shouldn't affect the notification.

Is what I meant by 'Kore closed' (apologies for confusing the terminology).

When Kore is removed from recent apps (the card is swiped away) the notification no longer updates or responds to changes in what is now playing as described in your response and does not disappear until a) some unspecified time later (which I assumed was an OS reap?) or b) Kore is re-opened.

It's as though it 'freezes' in the last state Kore knew about before it was removed from recent apps.

**Comment by SyncedSynapse** [comment]
Thanks for spotting this. There was indeed a bug that was causing it not to update in that situation.

It's fixed on c423d15ec8ceab381b6d6085affb492ef34a8fc2, though i've also implemented removing the notification when the user removes the app from the recent apps. You were right, if the user is removing the app he expects the notification to disappear also.

If you find any more issues, please report them.
