### ISSUE TITLE
Using the remote arrows to skip forward/backwards

### ISSUE THREAD

**Issue by tasn** [SyncedSynapse/Kore#4]
Hey,

Thanks for writing this app. It's significantly better than the rest and it's open source. Good work there. I have one suggestion though:

In the official xbmc remote app (the old unmaintained one), using the left/right arrow keys on the remote skips 30 seconds and the up/down 10 minutes. This is very useful for quickly skipping to a location in a film. Using fast forward is just not as good.

Thanks.

**Comment by Fiddl3** [comment]
You can always use progressbar

**Comment by tasn** [comment]
Oh, thanks, that's great. :)
Wasn't in the main remote page so wasn't visible. I guess you can close this ticket if you wish. For all I'm concerned, the usability issue is no longer there. Thanks.
